crud app/Models/ErrorViewModel.cs
namespace crud_app.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

crud app/Models/Fruit.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace crud_app.Models
{
    public class Fruit
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
    }
}

crud app/Controllers/FruitsController.cs
using crud_app.Data;
using crud_app.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.Internal;

namespace crud_app.Controllers
{
    public class FruitsController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public FruitsController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            var list =  _dbContext.Fruits.ToList();
            return View(list);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Fruit fruits) 
        {
            _dbContext.Fruits.Add(fruits);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id) 
        {
            var list = _dbContext.Fruits.Where(fr => fr.Id == id).FirstOrDefault();
            return View(list);
        }
        [HttpPost]
        public IActionResult Edit(Fruit fruits)
        {
            var update = _dbContext.Fruits.Find(fruits.Id);
            update.Name = fruits.Name;
            update.Price = fruits.Price;
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int Id)
        {
            var data = _dbContext.Fruits.Find(Id);
            _dbContext.Fruits.Remove(data);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Back()
        { 
            return RedirectToAction("Index");
        }
    }
}

crud app/Controllers/HomeController.cs
using crud_app.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace crud_app.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

crud app/Views/Fruits/Create.cshtml
<form asp-action="Create" asp-controller="Fruits" method="Post">
    <label>Name</label>
    <input type="text" name="name" class="form-control" />
    <label>Price</label>
    <input type="text" name="price" class="form-control" /> <br />
    <button type="submit" class="btn btn-success">Add</button>
    <a class="btn btn-secondary" asp-action="Back" asp-controller="Fruits">Back</a>
</form>

crud app/Views/Fruits/Edit.cshtml
@model Fruit

<form asp-action="Edit" asp-controller="Fruits" method="Post">
    <input name="Id" value="@Model.Id" hidden/>
    <label>Name</label>
    <input type="text" name="Name" class="form-control" value="@Model.Name"/>
    <label>Price</label>
    <input type="text" name="Price" class="form-control" value="@Model.Price"/><br />
    <button type="submit" class="btn btn-success"> Save Changes</button>
    <a class="btn btn-secondary" asp-action="Back" asp-controller="Fruits">Back</a>
</form>

crud app/Views/Fruits/Index.cshtml
@model List<Fruit>
@{
    int sn = 1;
}

<h1> List of Fruits</h1>
    <a class="btn btn-primary" asp-action="Create" asp-controller="Fruits">Create</a>
<table class="table"> 
    <thead>
        <tr>
            <th>SN</th>
            <th>Name</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var data in Model)
        {
            <tr>
                <td>@(sn++)</td>
                <td>@(data.Name)</td>
                <td>@(data.Price)</td>
                <td>
                    <a class="btn btn-warning" asp-action="Edit" asp-controller="Fruits" asp-route-id="@data.Id">Edit</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-controller="Fruits" asp-route-id="@data.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

crud app/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

crud app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - crud_app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/crud_app.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">crud_app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - crud_app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>